// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-notes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_notes_default = defineTool({
  name: "list_notes",
  title: "List knowledge notes",
  description: "List the signed-in user's knowledge notes from the Studio, most recently updated first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many notes to return (default 20)."),
    search: z.string().optional().describe("Optional case-insensitive substring to match against title.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("knowledge_notes").select("id,title,category,tags,updated_at,is_pinned,is_favorite,word_count").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (search) q = q.ilike("title", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-note.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_note_default = defineTool2({
  name: "get_note",
  title: "Get knowledge note",
  description: "Fetch a single knowledge note (including its structured AI content) by id.",
  inputSchema: { id: z2.string().uuid().describe("Note UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("knowledge_notes").select("*").eq("id", id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Note not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/create-note.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_note_default = defineTool3({
  name: "create_note",
  title: "Create knowledge note",
  description: "Create a new knowledge note in the signed-in user's Studio with raw text content.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Note title."),
    content: z3.string().trim().min(1).describe("Raw note content (markdown or plain text)."),
    category: z3.string().optional().describe("Optional category label."),
    tags: z3.array(z3.string()).optional().describe("Optional list of tags.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, category, tags }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("knowledge_notes").insert({
      user_id: ctx.getUserId(),
      title,
      content,
      category: category ?? null,
      tags: tags ?? [],
      word_count: content.split(/\s+/).filter(Boolean).length
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created note ${data.id}` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/search-history.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_history_default = defineTool4({
  name: "search_history",
  title: "Search historical events",
  description: "Search the archive's historical events by title or description substring.",
  inputSchema: {
    query: z4.string().trim().min(1).describe("Text to search for in event title/description."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results (default 15).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("historical_events").select("id,slug,title,year,year_label,category,description,significance").or(`title.ilike.%${query}%,description.ilike.%${query}%`).order("significance", { ascending: false, nullsFirst: false }).limit(limit ?? 15);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-bookmarks.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bookmarks_default = defineTool5({
  name: "list_bookmarks",
  title: "List bookmarks",
  description: "List the signed-in user's saved event/era bookmarks.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb5(ctx).from("bookmarks").select("id,event_id,era_id,note,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { bookmarks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "viqlsemgpkioassndauo";
var mcp_default = defineMcp({
  name: "epoch-chronicle-mcp",
  title: "Epoch Chronicle",
  version: "0.1.0",
  instructions: "Access the signed-in user's Universal History Archive. Use `search_history` to query historical events, `list_notes`/`get_note`/`create_note` for the user's Studio knowledge notes, and `list_bookmarks` for saved events.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_history_default, list_notes_default, get_note_default, create_note_default, list_bookmarks_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
